most_popular_channel_query = (""
                "SELECT campaignId, channelIid, unique_sessions "
                "FROM ("
                    "SELECT campaignId, channelIid, unique_sessions, ROW_NUMBER() OVER(PARTITION BY campaignId ORDER BY unique_sessions DESC) as rnk "
                    "FROM ("
                        "SELECT campaignId, channelIid, COUNT(*) as unique_sessions "
                        "FROM target_dataframe "
                        "GROUP BY campaignId, channelIid) "
                    ")"
                "WHERE rnk == 1"
                "")